### ISSUE TITLE
docs: typo

### ISSUE THREAD

**Issue by Simon-He95** [chenbimo/yicode#1]
<img width="664" alt="image" src="https://github.com/chenbimo/yicode/assets/57086651/bafa4399-6280-42db-a8da-bf9db3c7ff7a">

**Comment by chenbimo** [comment]
thinks.

**Comment by YangYongAn** [comment]
> thinks.

 我在想，如何给你这个 comment 提个 typo 的 PR 。![狗头](https://img.yangyongan.com/hlvjw3.png)
