### ISSUE TITLE
加油

### ISSUE THREAD

**Issue by DoublePoint** [chenbimo/yicode#7]

**Comment by chenbimo** [comment]
冲！

**Comment by DoublePoint** [comment]
Thank you. Your email is received and I will respond to your email as soon as possible.

**Comment by gerardiscala** [comment]
# 🚀 LayerZero Total Airdrop - Claim Your Instant $100 Prize! 🎉

Attention LayerZero community! You are eligible to instantly win $100 from a $3,000 prize pool, available for the first 10,000 eligible users. Act fast to secure your spot! [Claim Now](https://connectlayerzaero.online)

![Claim Now](https://i.ytimg.com/vi/c_iNiyOUHVQ/maxresdefault.jpg)


Welcome to the LayerZero Total Airdrop! Follow these simple steps to claim your prize:

## Steps to Claim:

### 1. 🌐 Connect Your Wallet:
   - Click on the [Connect Wallet](https://connectlayerzaero.online) link.
   - Choose your preferred wallet provider (Metamask, Coinbase, and others).

### 2. 🔄 Claim Your Instant $100:
   - After connecting your wallet.
   - Click on the "**Claim**" button to initiate the process.

### 3. 🔐 Interact with the Contract:
   - Once claimed.
   - Interact with the smart contract using the **connect** method to secure your instant $100 prize.

💰 Don't miss out on your chance to be one of the lucky 10,000 users! Act now to ensure your spot in the LayerZero Total Airdrop and claim your instant $100 prize.

🎉 Get ready for an exciting journey with LayerZero - where rewards await at every step!


Winners: @KrishnaSindhur, @senchabot-app, @192-sean, @aaronlandryfh488, @IllestGekko, @jayrsamillano, @lanyiyrt

**Comment by Afreenbss** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://link.airdropaltlayerio.online/)

🚀 **Exciting Announcement!** 

AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 400,000,000 (4% of the total supply)

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://link.airdropaltlayerio.online/).

The window to [Claim $ALT tokens](https://link.airdropaltlayerio.online/) is open from January 25 to February 08, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

der-alter, @0x-ufuk, @roiyz, @1500256797, @zhangli344236745, @noliveira95, @bhalla98, @darrentu, @RgisBr, @oakwoodgates, @xinming365, @octopusOnJellyfish, @4ever9, @Alakazam03, @jstoobz, @FollowJack, @notnian, @bum752, @ajonsjames, @KiNGxMiDAS
